name: Deploy Lambda Function
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: build project
        run: mvn -B package --file pom.xml
      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: create lambda function
        run: |
          aws lambda create-function --function-name course-function --runtime java21 --handler org.example.StreamLambdaHandler::handleRequest --role arn:aws:iam::190044383502:role/lamdba-cicid-roles --zip-file fileb://target/course-service-1.0-SNAPSHOT-lambda-package.zip
        continue-on-error: true
      - name: update lambda function
        run: |
          aws lambda update-function-code --function-name course-function --zip-file fileb://target/course-service-1.0-SNAPSHOT-lambda-package.zip
   #   - name: Update API Gateway with OpenAPI definition
   #     run: |
   #       aws apigateway put-rest-api --rest-api-id ${{ secrets.API_GATEWAY_ID }} --body "$(cat openapi.json | base64 --wrap=0)"
   #   - name: Deploy API Gate
   #     run: |
   #       aws apigateway create-deployment --rest-api-id ${{ secrets.API_GATEWAY_ID }}
            
